More debug output to ensure package.json changes are written.

diff --git a/version-bump-publish/action.yml b/version-bump-publish/action.yml
--- a/version-bump-publish/action.yml
+++ b/version-bump-publish/action.yml
@@ -195,14 +195,25 @@ runs:
     env:
       PACKAGE_WITH_VERSION: ${{ steps.bump-version.outputs.fullVersion }}
       REQUIRES_PR: ${{ inputs.requiresPr == 'true' }}
+      NEXT_VERSION_NUMBER: ${{ steps.get-latest-version.outputs.nextVersion }}
     shell: bash
     run: |
       echo "Current git status in commit step: "
       git status
 
-      echo "Committing $PACKAGE_WITH_VERSION package.json changes"
+      CONFIRMED_PACKAGE_VERSION_NUMBER=$(cat package.json | jq -r '.version')
+      echo "Confirmed packags.json was written with version $CONFIRMED_PACKAGE_VERSION_NUMBER - should be $NEXT_VERSION_NUMBER"
+      if [ "$CONFIRMED_PACKAGE_VERSION_NUMBER" != "$NEXT_VERSION_NUMBER" ]; then
+        echo "Error: package.json was not written with the expected version number"
+        exit 1
+      fi
+
+      echo "Adding package.json and package-lock.json to git index"
       git add package.json package-lock.json
+
+      echo "Committing $PACKAGE_WITH_VERSION package.json changes"
       git commit -m "Update $PACKAGE_NAME to $PACKAGE_WITH_VERSION"
+
       # git pull --rebase
       echo "Pushing to $WORKING_BRANCH without tags..."
       git push -u origin $WORKING_BRANCH
